# Deploy Python server
---
- name: "Pull code"
  git:
    repo={{ site_repo }}
    dest=/srv/http/{{ site_hostname }}/src/
  register: checkout

- name: "{{ site_repo }}: Prep virtualenv"
  pip:
    requirements="/srv/http/{{site_hostname}}/src/requirements.txt"
    virtualenv="/srv/http/{{ site_hostname }}/venv"
  when:
    checkout.changed

- name: "Bounce unicorn"
  command:
    /srv/http/{{ site_hostname }}/src/graceful.sh
  when:
    checkout.changed

  
